name: Test

on:
  push:
    branches:
      - "*"
      - "!main"
      - "!skipci*"

concurrency:
  group: ${{ github.ref_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STAGE_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
