name: Test

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      STAGE_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: echo $STAGE_NAME
